playground/ExampleSandpack.tsx
playground/learn/mutations.tsx
playground/learn/queries.tsx
playground/learn/signals.tsx
playground/learn/stores.tsx
src/StoresProvider.tsx

Refactored import statements and replaced useApi with useStore in several files.

refactor: Refactor impact-app imports and useStore

---

package.json
src/StoresProvider.tsx

Updated version in package.json and changed type declaration in StoresProvider.tsx

fix: Update package.json and StoresProvider.tsx

---

README.md

Fixed broken YouTube link in README.md that was pointing to the wrong URL.

fix: Fixed broken YouTube link in README.md

---

docs/03_Understanding_The_Design.md

Refactors the wording and clarifies the concepts of state and state management in React.

refactor: Refactor state and management in React

---

package.json
src/debugger.ts

Fixes formatting issues and adds missing commas and semicolons

refactor: Fix and refactor code formatting

---

README.md

Add composition model for any state primitive (WIP)

feat: Add composition model for state primitive

---

package.json

Update package.json version from 0.31.1 to 0.32.0

feat: Update package version

---

playground/ExampleSandpack.tsx
playground/learn/stores.tsx

Update impact-app version from 0.30.0 to 0.32.0 and refactor createStoresProvider to createScopeProvider

feat: Update impact-app version and refactor createStoresProvider

---

playground/examples/dataFetching.tsx
playground/examples/routing.tsx
playground/examples/visibility.tsx
playground/examples/xstate.tsx

Update import statements to use 'useStore' instead of 'createStore' in multiple files

feat: Update import statements

---

playground/learn/stores.tsx

Changed store providers to scopes for scoping state and logic to specific pages and features of the application.

feat: Updated store providers to scopes

---

docs/05_API.md
docs/07_Scopes.md
package.json
src/Query.ts

Updates the refetch behavior in the Query class with a new `refetch` property

feat: Update refetch behavior in Query

---

package.json
yarn.lock

Add react dependency in package.json

feat: Add React dependency

---

package.json
src/Signal.ts

Add currentAbortController and abort signal if aborted

feat: Update package version to 0.36.1

---

package.json
src/stores.tsx

Update package.json version from 0.36.1 to 0.36.2

feat: Update version

---

package.json
src/context.tsx

Remove unnecessary shouldComponentUpdate method

fix: Increment package version

---

docs/02_The_Primitives.md
docs/03_Understanding_The_Design.md
docs/04_Hello_World.md
docs/05_API.md
docs/06_Contexts.md
docs/07_Reactivity.md
docs/08_Queries_And_Mutations.md

Added reactive state primitives, context providers, and hooks for state and asynchronous processes.

feat: Added reactive state primitives and context providers

---

package.json
src/signal.ts

Updated package.json version from 0.37.4 to 0.37.5 and updated signal getter in ObserverContext

feat: Updated version and signal getter in ObserverContext

---

context/README.md
context/package.json
signal/README.md
signal/package.json
signal/src/signal.ts

Updated package names and imports to remove '@impact' namespace

feat: Updated package names and imports

---

context/package.json
signal/package.json

Update package.json version and file paths for context and signal

feat: Update version and file paths

---

.codesandbox/tasks.json
package.json
signal/package.json
signal/src/signal.ts
yarn.lock

Update eslint-plugin-react version, update signal package version, and refactor signal.ts file

feat: Update dependencies and signal.ts file

---

signal/package.json
signal/src/signal.ts

Update package version from 0.1.2 to 0.1.3. Change 'SignalPromise' type to 'PromiseSignal'. Update function signatures accordingly.

feat: Update version and type definition in Signal package

---

signal/package.json
signal/src/signal.ts

Update signal version from 0.1.3 to 0.1.4 and add 'updater' function

feat: Update signal version to 0.1.4

---

README.md

Added impact-context and impact-signal to the README.md file

feat: Added reactive context provider and signal primitive

---

signal/README.md
signal/src/signal.ts

Replace 'observe' with 'effect' in signal module

feat: Replace observe with effect

---

signal/src/debugger.ts

Update import path for SignalTracker module in debugger.ts

feat: Update import path in debugger.ts

---

app/package.json
context/package.json
context/src/index.tsx

Update package versions and import statements in the codebase

feat: Update package and import statements

---

app/README.md
app/package.json
app/src/index.ts
app/src/store.ts
signal/package.json
signal/src/index.ts

Combines `impact-app` and `impact-signal` and improves developer experience by automatically observing signals accessed by components, cleaning up effects on unmount, and providing a file and folder structure for organizing contexts.

feat: Enhance developer experience with automatic observability

---

app/README.md

Application example added with registration note

feat: Add Example application

---

impact-app/package.json
impact-app/src/signal.ts

Fix version, remove commented code, add signal debug hooks, fix, currentSubscriptionDisposer type, fix currentSubscriptionDisposer cleanup and remove commented code

feat: Memory review and small refactors

---

docs/01_tutorial.md

Fixes a typo in the method name

fix(tutorial): Method name typo

---

docs/01_tutorial.md

Add new possibilities for managing complexity and formatting changes in the tutorial

docs: Update tutorial

---

impact-app/package.json
impact-app/src/signal.ts

Update package.json version and refactor Signal type definition

fix: Typing issue with signal

---

impact-debugger/package.json
impact-debugger/src/index.ts

Update package.json version from 0.1.2 to 0.1.3, add cleanFunctionName function and format console.log statement

feat: fix formatting issues and clean function names

---

docs/06_debugger.md
package.json
yarn.lock

Add FAQ section to debugger docs, update debugger start instructions, update debugger file open instructions and update package.json

docs: Update debugger docs

---

.codesandbox/tasks.json
.devcontainer/devcontainer.json

Add runAtStart property, remove duplicate runAtStart property from tasks.json, add devcontainer.json file, add Node.js & TypeScript dev container configuration and fix image version

feat: Move to CSB workspace

---

impact-debugger/package.json
impact-debugger/src/index.ts
impact-debugger/src/ui/index.tsx

Add holding shift state and event listener, change shift press duration to 300ms, modify csbFocusFile function call, update UI for workspace path input and update UI for copy path/hint

feat: Use workspace path also on CSB

---

impact-debugger/package.json
impact-debugger/src/index.ts

Update impact-debugger version to 0.2.9 and add console logs for pinpointing stackframe and result

feat: debug more

---

impact-debugger/package.json
impact-debugger/src/index.ts

Update package version from 0.2.10 to 0.2.12 and refactor index.ts code

fix: debug stuff

---

dev/src/index.tsx
impact-app/package.json
impact-app/src/signal.ts
impact-debugger/package.json
impact-debugger/src/index.ts
impact-debugger/src/ui/index.tsx

Fix version, add getActiveContextContainer, comment out console.log statement, add flattenObservers function and refactor CodeReference rendering

fix: Do not track during context resolvement and flatten observers in debugger

---

dev/src/index.tsx
impact-app/package.json
impact-app/src/signal.ts
impact-debugger/package.json
impact-debugger/src/ui/index.tsx
impact-debugger/src/ui/styles.ts

Fix count initialization, add runDerived property, update font size and spacing, update package.json version and update signal.ts subscription

feat: Fix observer context updates and debugger timeline

---

dev/src/index.tsx
impact-app/package.json
impact-app/src/signal.ts
impact-debugger/package.json
impact-debugger/src/index.ts
impact-debugger/src/ui/index.tsx

Fix bug with setTimeout, add effect for logging foo value, refactor JSX, update version, update onGetValue function signature, add stack property and refactor stack handling

feat: Improve effects stack traces

---

impact-app/package.json
impact-debugger/package.json

Bump impact-app version to 0.49.0 and bump impact-debugger version to 0.4.0

fix: Bump versions

---

docs/01_tutorial.md
docs/05_context.md

Fixed typo, added globalContext usage and added globalContext example

feat: Updated docs

---

.github/workflows/deploy.yml

Remove .npmrc file as it is only used for local publish, change NPM_TOKEN variable reference to use secrets in deploy workflow and build with VitePress while installing dependencies

feat: blah

---

docs/.vitepress/theme/Playground.vue
docs/advanced/lists.md
docs/index.md
docs/learn/closures.md
docs/learn/composable-store.md
docs/learn/context.md
docs/learn/derived.md
docs/learn/effects.md
docs/learn/index.md
docs/learn/promises.md
docs/learn/props.md
docs/learn/scoping.md
docs/learn/signals.md
docs/learn/store.md
package.json
preBuild.mjs

Update imports  to include file extensions, add ClientOnly components to various markdown files, update link paths  file and add preBuild.mjs script

fix: Fix build issues

---

docs/.vitepress/theme/Playground.vue

Let's use the blazing-fast new bundler

Sandack: Add experimental bundler

---

docs/learn/closures.md
docs/learn/composable-store.md
docs/learn/context.md
docs/learn/derived.md
docs/learn/effects.md
docs/learn/index.md
docs/learn/promises.md
docs/learn/props.md
docs/learn/scoping.md
docs/learn/signals.md
docs/learn/store.md

Refactor code formatting ` and `store.md` for consistency and readability and update language and improve clarity ` and `props.md` for better understanding

fix: Iterate learning docs

---

docs/.vitepress/theme/Playground.vue
impact-react-debugger/README.md
impact-react-debugger/package.json
impact-react/README.md
impact-react/package.json

Updated bundlerURL, enhanced README.md in impact-react-debugger, updated package.json version to 1.0.1 in impact-react-debugger, enhanced README.md in impact-react and updated package.json version to 1.2.1 in impact-react

fix: Fix bundler url and readmeas

---

docs/.vitepress/config.mts
docs/advanced/lists.md
docs/advanced/queries-and-mutations.md
docs/cleanup.md
docs/derived.md
docs/effect.md
docs/signal.md
docs/store.md

Add cleanup functionality to manage subscriptions and dispose of resources in component trees

feat: Update docs

---

docs/.vitepress/config.mts
docs/createStoreProvider.md
docs/index.md
docs/useStore.md

Update links  from /store to /useStore, add createStoreProvider.md with detailed information and add useStore.md with usage details

fix: Lower case api reference and split up more

---

docs/learn/context.md
docs/learn/data-fetching.md
docs/signal.md

Updated links , data-fetching.md, and signal.md to point to the correct React references.

fix: Links

---

docs/learn/context.md
docs/learn/scoping.md

Update store to receive props from provider for initialization with a focus on modern React data fetching patterns.

fix: typos 

---

docs/.vitepress/theme/Playground.vue
docs/.vitepress/theme/custom.css

- Changed logo background
- Fix border collapse on sandpack
- Sticky iframe inside sandpack
- Other small tweaks

style: layout tweak

---

docs/.vitepress/theme/Playground.vue
docs/learn/context.md
docs/learn/props.md

Update styles for cm-lineNumbers, correct the order of points and fix typo

fix: typos and line number color

---

docs/index.md

Updated details  to include more information about Impacts modern reactive model and Reacts component model.

feat: improve messaging

---

docs/learn/effects.md

Add conditional alert when count is equal to 5 in Impact effect and update Impact effect usage to clarify its purpose

feat: improve effects docs

---

docs/.vitepress/theme/custom.css
docs/learn/effects.md
docs/learn/props.md

Update custom.css to set max-width

style:  docs and bg image

---

docs/.vitepress/theme/Playground.vue
docs/learn/context.md
docs/learn/effects.md

Fix autofocus attribute, updated setCount function  to use callback function and refactor effects.md to improve clarity and discourage the use of effects

feat: More text fixes and removed autofocus of playground

---

impact-react/package.json
impact-react/src/store.ts

Update package.json version from 1.2.3 to 1.2.4 and add error message when store is not provided on context

feat: Improve error message
